- name: Setup postgresql master servers
  hosts: postgresql_master
  become: true
  roles:
    - postgresql

- name: Setup postgresql replica servers
  hosts: postgresql_replica
  become: true
  roles:
    - postgresql
