---
all:
  children:
    postgresql:
      children:
        postgresql_master:
          hosts:
            server1:
              ansible_host: 192.168.56.40
              ansible_user: vagrant
              ansible_password: vagrant
        postgresql_replica:
          hosts:
            server2:
              ansible_host: 192.168.56.41
              ansible_user: vagrant
              ansible_password: vagrant
